# Generated by Django 4.2 on 2026-01-30 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Bookingstatuses',
                'db_table': 'events"."BookingStatus',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('motive', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'events',
                'db_table': 'events"."Event',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('holiday_type', models.CharField(choices=[('fixed', 'Fixed'), ('unfixed', 'Unfixed')], default='unfixed', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Holidays',
                'db_table': 'events"."Holidays',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'rooms',
                'db_table': 'events"."Rooms',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('members', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'tours',
                'db_table': 'events"."Tours',
            },
        ),
        migrations.CreateModel(
            name='BookSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('booking_type', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.room')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.bookingstatus')),
            ],
            options={
                'verbose_name_plural': 'BookingSlots',
                'db_table': 'events"."BookingSlots',
            },
        ),
    ]
