# Generated by Django 4.2 on 2026-02-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_bookslot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date'], 'verbose_name': 'holiday', 'verbose_name_plural': 'holiday'},
        ),
    ]
