# Generated by Django 4.2 on 2026-02-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_holiday_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
