# Generated by Django 4.2 on 2026-02-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_delete_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('holiday_type', models.CharField(choices=[('fixed', 'Fixed'), ('unfixed', 'Unfixed')], default='unfixed', max_length=10)),
            ],
            options={
                'db_table': 'events"."Holiday',
                'ordering': ['date'],
            },
        ),
    ]
