# Generated by Django 4.2 on 2026-02-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_bookslot_date_created_at_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookslot',
            new_name='Slots_date_b218d2_idx',
            old_name='bookslot_date_created_idx',
        ),
    ]
