# Generated by Django 4.2 on 2026-03-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_meeting_remove_users_add_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group Meeting')], max_length=20),
        ),
    ]
