# Generated by Django 4.2 on 2026-03-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_add_product_model'),
        ('events', '0015_delete_event_and_meeting_state_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Event', max_length=255)),
                ('motive', models.TextField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Event',
                'db_table': 'events"."event',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group Meeting')], max_length=20)),
                ('time', models.SmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meeting_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.room')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='project.product')),
            ],
            options={
                'db_table': 'events"."MeetingPush',
                'ordering': ['-created_at', 'is_active'],
            },
        ),
    ]
