# Generated by Django 4.2 on 2026-03-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional; required when status is set to Done.', null=True),
        ),
    ]
