# Generated by ChatGPT on 2026-03-23
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_bookslot_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='need_more_discussion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='dispute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='in_future',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='deliverable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='not_deliverable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='opportunity',
            field=models.TextField(blank=True, null=True),
        ),
    ]

