# Generated by Django 4.2 on 2026-04-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_bookslot_done_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='member_name',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
