# Generated by Django 4.2 on 2026-04-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete: set by DELETE /api/jobs/{id}/; row is not removed from DB.', null=True),
        ),
    ]
