# Generated by Django 4.2 on 2026-04-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_jobopening_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
