# Generated by Django 4.2 on 2026-02-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0022_task_created_by_created_at_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_created_ed71e5_idx',
            old_name='task_created_by_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_created_223562_idx',
            old_name='task_created_by_type_idx',
        ),
    ]
