# Generated by Django 4.2 on 2026-02-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0023_rename_task_created_by_created_at_idx_tasks_created_ed71e5_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_by', '-created_at', 'due_date'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
