# Generated by Django 4.2 on 2026-03-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0024_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmessage',
            name='seen',
        ),
    ]
