# Generated by Django 6.0.4 on 2026-04-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StructureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('boq', 'BOQ Physical'), ('lidar', 'LiDAR'), ('sar', 'SAR')], max_length=20)),
                ('team_lead_name', models.CharField(max_length=120)),
                ('branch', models.CharField(default='INFRA_CORE', max_length=80)),
                ('date_of_entry', models.DateField()),
                ('route_corridor', models.CharField(blank=True, max_length=200)),
                ('sr_no', models.CharField(blank=True, max_length=40)),
                ('chainage', models.CharField(max_length=120)),
                ('structure_type', models.CharField(max_length=100)),
                ('length_of_structure', models.CharField(blank=True, max_length=120)),
                ('span_arrangement', models.CharField(blank=True, max_length=200)),
                ('equipment_notes', models.TextField(blank=True)),
                ('inspection_status', models.CharField(choices=[('Completed', 'Completed'), ('Missing', 'Missing'), ('In progress', 'In progress'), ('Issue-attention', 'Issue-attention')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('las_file_submitted', models.BooleanField(default=False)),
                ('reports_available_on_bms_for_las', models.BooleanField(default=False)),
                ('sar_files_submitted', models.BooleanField(default=False)),
                ('reports_available_on_bms_for_sar', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', '-created_at'], name='infra_forms_module_e44328_idx'), models.Index(fields=['date_of_entry'], name='infra_forms_date_of_82df45_idx')],
            },
        ),
    ]
