# Generated by Django 6.0.4 on 2026-04-21 04:49

import django.db.models.deletion
from django.db import migrations, models


def backfill_route_groups(apps, schema_editor):
    StructureEntry = apps.get_model("infra_forms", "StructureEntry")
    RouteCorridorGroup = apps.get_model("infra_forms", "RouteCorridorGroup")
    for entry in StructureEntry.objects.exclude(route_corridor=""):
        text = (entry.route_corridor or "").strip()
        if not text:
            continue
        key = text.casefold()
        group, _ = RouteCorridorGroup.objects.get_or_create(
            module=entry.module,
            route_key=key,
            defaults={"route_label": text},
        )
        entry.route_group_id = group.id
        entry.route_corridor = group.route_label
        entry.save(update_fields=["route_group_id", "route_corridor"])


def backfill_route_groups_reverse(apps, schema_editor):
    StructureEntry = apps.get_model("infra_forms", "StructureEntry")
    StructureEntry.objects.update(route_group_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('infra_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCorridorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('boq', 'BOQ Physical'), ('lidar', 'LiDAR'), ('sar', 'SAR')], max_length=20)),
                ('route_key', models.CharField(db_index=True, max_length=200)),
                ('route_label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['route_label'],
                'constraints': [models.UniqueConstraint(fields=('module', 'route_key'), name='infra_routegroup_module_routekey_uniq')],
            },
        ),
        migrations.AddField(
            model_name='structureentry',
            name='route_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_entries', to='infra_forms.routecorridorgroup'),
        ),
        migrations.AddIndex(
            model_name='structureentry',
            index=models.Index(fields=['module', 'route_group'], name='infra_forms_module_0ee458_idx'),
        ),
        migrations.RunPython(backfill_route_groups, backfill_route_groups_reverse),
    ]
