# Generated by Django 6.0.4 on 2026-04-21 05:00

import django.db.models.deletion
from django.db import migrations, models


def copy_structure_entries_to_module_tables(apps, schema_editor):
    Old = apps.get_model("infra_forms", "StructureEntry")
    Boq = apps.get_model("infra_forms", "BoqStructureEntry")
    Lidar = apps.get_model("infra_forms", "LidarStructureEntry")
    Sar = apps.get_model("infra_forms", "SarStructureEntry")
    by_module = {"boq": Boq, "lidar": Lidar, "sar": Sar}
    for row in Old.objects.all():
        Target = by_module.get(row.module)
        if Target is None:
            continue
        Target.objects.create(
            route_group_id=row.route_group_id,
            team_lead_name=row.team_lead_name,
            branch=row.branch,
            date_of_entry=row.date_of_entry,
            route_corridor=row.route_corridor or "",
            sr_no=row.sr_no or "",
            chainage=row.chainage,
            structure_type=row.structure_type,
            length_of_structure=row.length_of_structure or "",
            span_arrangement=row.span_arrangement or "",
            equipment_notes=row.equipment_notes or "",
            inspection_status=row.inspection_status,
            remark=row.remark or "",
            las_file_submitted=row.las_file_submitted,
            reports_available_on_bms_for_las=row.reports_available_on_bms_for_las,
            sar_files_submitted=row.sar_files_submitted,
            reports_available_on_bms_for_sar=row.reports_available_on_bms_for_sar,
            created_at=row.created_at,
            updated_at=row.updated_at,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('infra_forms', '0002_routecorridorgroup_structureentry_route_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoqStructureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_lead_name', models.CharField(max_length=120)),
                ('branch', models.CharField(default='INFRA_CORE', max_length=80)),
                ('date_of_entry', models.DateField()),
                ('route_corridor', models.CharField(blank=True, max_length=200)),
                ('sr_no', models.CharField(blank=True, max_length=40)),
                ('chainage', models.CharField(max_length=120)),
                ('structure_type', models.CharField(max_length=100)),
                ('length_of_structure', models.CharField(blank=True, max_length=120)),
                ('span_arrangement', models.CharField(blank=True, max_length=200)),
                ('equipment_notes', models.TextField(blank=True)),
                ('inspection_status', models.CharField(choices=[('Completed', 'Completed'), ('Missing', 'Missing'), ('In progress', 'In progress'), ('Issue-attention', 'Issue-attention')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('las_file_submitted', models.BooleanField(default=False)),
                ('reports_available_on_bms_for_las', models.BooleanField(default=False)),
                ('sar_files_submitted', models.BooleanField(default=False)),
                ('reports_available_on_bms_for_sar', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BOQ structure entry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LidarStructureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_lead_name', models.CharField(max_length=120)),
                ('branch', models.CharField(default='INFRA_CORE', max_length=80)),
                ('date_of_entry', models.DateField()),
                ('route_corridor', models.CharField(blank=True, max_length=200)),
                ('sr_no', models.CharField(blank=True, max_length=40)),
                ('chainage', models.CharField(max_length=120)),
                ('structure_type', models.CharField(max_length=100)),
                ('length_of_structure', models.CharField(blank=True, max_length=120)),
                ('span_arrangement', models.CharField(blank=True, max_length=200)),
                ('equipment_notes', models.TextField(blank=True)),
                ('inspection_status', models.CharField(choices=[('Completed', 'Completed'), ('Missing', 'Missing'), ('In progress', 'In progress'), ('Issue-attention', 'Issue-attention')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('las_file_submitted', models.BooleanField(default=False)),
                ('reports_available_on_bms_for_las', models.BooleanField(default=False)),
                ('sar_files_submitted', models.BooleanField(default=False)),
                ('reports_available_on_bms_for_sar', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LiDAR structure entry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SarStructureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_lead_name', models.CharField(max_length=120)),
                ('branch', models.CharField(default='INFRA_CORE', max_length=80)),
                ('date_of_entry', models.DateField()),
                ('route_corridor', models.CharField(blank=True, max_length=200)),
                ('sr_no', models.CharField(blank=True, max_length=40)),
                ('chainage', models.CharField(max_length=120)),
                ('structure_type', models.CharField(max_length=100)),
                ('length_of_structure', models.CharField(blank=True, max_length=120)),
                ('span_arrangement', models.CharField(blank=True, max_length=200)),
                ('equipment_notes', models.TextField(blank=True)),
                ('inspection_status', models.CharField(choices=[('Completed', 'Completed'), ('Missing', 'Missing'), ('In progress', 'In progress'), ('Issue-attention', 'Issue-attention')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('las_file_submitted', models.BooleanField(default=False)),
                ('reports_available_on_bms_for_las', models.BooleanField(default=False)),
                ('sar_files_submitted', models.BooleanField(default=False)),
                ('reports_available_on_bms_for_sar', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SAR structure entry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='structureentry',
            name='infra_forms_module_e44328_idx',
        ),
        migrations.RemoveIndex(
            model_name='structureentry',
            name='infra_forms_date_of_82df45_idx',
        ),
        migrations.RemoveIndex(
            model_name='structureentry',
            name='infra_forms_module_0ee458_idx',
        ),
        migrations.AddField(
            model_name='boqstructureentry',
            name='route_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='infra_forms.routecorridorgroup'),
        ),
        migrations.AddField(
            model_name='lidarstructureentry',
            name='route_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='infra_forms.routecorridorgroup'),
        ),
        migrations.AddField(
            model_name='sarstructureentry',
            name='route_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='infra_forms.routecorridorgroup'),
        ),
        migrations.RunPython(copy_structure_entries_to_module_tables, noop_reverse),
        migrations.RemoveField(
            model_name='structureentry',
            name='route_group',
        ),
        migrations.AddIndex(
            model_name='boqstructureentry',
            index=models.Index(fields=['-created_at'], name='infra_forms_created_c0f7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='boqstructureentry',
            index=models.Index(fields=['date_of_entry'], name='infra_forms_date_of_05b674_idx'),
        ),
        migrations.AddIndex(
            model_name='boqstructureentry',
            index=models.Index(fields=['route_group'], name='infra_forms_route_g_8cd0db_idx'),
        ),
        migrations.AddIndex(
            model_name='lidarstructureentry',
            index=models.Index(fields=['-created_at'], name='infra_forms_created_79f660_idx'),
        ),
        migrations.AddIndex(
            model_name='lidarstructureentry',
            index=models.Index(fields=['date_of_entry'], name='infra_forms_date_of_0e513f_idx'),
        ),
        migrations.AddIndex(
            model_name='lidarstructureentry',
            index=models.Index(fields=['route_group'], name='infra_forms_route_g_fea61e_idx'),
        ),
        migrations.AddIndex(
            model_name='sarstructureentry',
            index=models.Index(fields=['-created_at'], name='infra_forms_created_83c969_idx'),
        ),
        migrations.AddIndex(
            model_name='sarstructureentry',
            index=models.Index(fields=['date_of_entry'], name='infra_forms_date_of_1b8fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='sarstructureentry',
            index=models.Index(fields=['route_group'], name='infra_forms_route_g_e4b423_idx'),
        ),
        migrations.DeleteModel(
            name='StructureEntry',
        ),
    ]
