# Generated by Django 6.0.4 on 2026-04-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra_forms', '0003_split_module_entry_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqstructureentry',
            name='branch',
            field=models.CharField(blank=True, default='INFRA_CORE', max_length=80),
        ),
        migrations.AlterField(
            model_name='boqstructureentry',
            name='chainage',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='boqstructureentry',
            name='date_of_entry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boqstructureentry',
            name='inspection_status',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('Completed', 'Completed'), ('Missing', 'Missing'), ('In progress', 'In progress'), ('Issue-attention', 'Issue-attention')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='boqstructureentry',
            name='structure_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='boqstructureentry',
            name='team_lead_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='lidarstructureentry',
            name='branch',
            field=models.CharField(blank=True, default='INFRA_CORE', max_length=80),
        ),
        migrations.AlterField(
            model_name='lidarstructureentry',
            name='chainage',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='lidarstructureentry',
            name='date_of_entry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lidarstructureentry',
            name='inspection_status',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('Completed', 'Completed'), ('Missing', 'Missing'), ('In progress', 'In progress'), ('Issue-attention', 'Issue-attention')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lidarstructureentry',
            name='structure_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lidarstructureentry',
            name='team_lead_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='sarstructureentry',
            name='branch',
            field=models.CharField(blank=True, default='INFRA_CORE', max_length=80),
        ),
        migrations.AlterField(
            model_name='sarstructureentry',
            name='chainage',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='sarstructureentry',
            name='date_of_entry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sarstructureentry',
            name='inspection_status',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('Completed', 'Completed'), ('Missing', 'Missing'), ('In progress', 'In progress'), ('Issue-attention', 'Issue-attention')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sarstructureentry',
            name='structure_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sarstructureentry',
            name='team_lead_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
