# Generated by Django 6.0.4 on 2026-04-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra_forms', '0004_optional_structure_entry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqstructureentry',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='lidarstructureentry',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='sarstructureentry',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
