# Generated by Django 6.0.4 on 2026-04-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra_forms', '0005_add_project_name_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
