# Generated by Django 4.2 on 2026-04-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra_forms', '0006_add_project_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraProjectForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(blank=True, default='', max_length=160)),
                ('creator', models.CharField(blank=True, default='', max_length=120)),
                ('date', models.DateField(blank=True, null=True)),
                ('MJB', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('MNB', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('VUP', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('PUP', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('BOX_Slab_Culvert', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('ROB', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('FO', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infra_project_forms', to='infra_forms.projectcatalog')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfraProjectFormEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('MJB', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('MNB', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('VUP', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('PUP', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('BOX_Slab_Culvert', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('ROB', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('FO', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='infra_forms.infraprojectform')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='infraprojectformentry',
            index=models.Index(fields=['form'], name='infra_forms_form_id_b57d80_idx'),
        ),
        migrations.AddIndex(
            model_name='infraprojectformentry',
            index=models.Index(fields=['date'], name='infra_forms_date_2c764e_idx'),
        ),
        migrations.AddIndex(
            model_name='infraprojectform',
            index=models.Index(fields=['projectname'], name='infra_forms_project_0e25a1_idx'),
        ),
        migrations.AddIndex(
            model_name='infraprojectform',
            index=models.Index(fields=['date'], name='infra_forms_date_10213e_idx'),
        ),
        migrations.AddIndex(
            model_name='infraprojectform',
            index=models.Index(fields=['project'], name='infra_forms_project_b004da_idx'),
        ),
    ]
