# Generated by Django 4.2 on 2026-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra_forms', '0007_infraprojectform_infraprojectformentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcatalog',
            name='service',
            field=models.CharField(blank=True, default='', help_text='Optional dropdown value (e.g. LiDAR/BOQ/SAR).', max_length=160),
        ),
    ]
