# Generated by Django 4.2 on 2026-04-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra_forms', '0008_projectcatalog_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraprojectformentry',
            name='status',
            field=models.CharField(blank=True, default='', help_text='Optional status value sent by frontend (static dropdown).', max_length=80),
        ),
    ]
