# Generated by Django 4.2 on 2026-05-08 08:55

import django.db.models.deletion
from django.db import migrations, models


def seed_service_types_and_backfill(apps, schema_editor):
    InfraServiceType = apps.get_model("infra_forms", "InfraServiceType")
    StructureEntry = apps.get_model("infra_forms", "StructureEntry")
    StructureEntryServiceState = apps.get_model("infra_forms", "StructureEntryServiceState")

    seeds = [
        ("boq", "BOQ Physical", 0),
        ("lidar", "LiDAR", 1),
        ("sar", "SAR", 2),
    ]
    type_by_code = {}
    for code, label, order in seeds:
        obj, _ = InfraServiceType.objects.get_or_create(
            code=code,
            defaults={"label": label, "sort_order": order, "active": True},
        )
        type_by_code[code] = obj

    for entry in StructureEntry.objects.iterator():
        for code, stype in type_by_code.items():
            status = (getattr(entry, f"{code}_status") or "").strip()
            remark = getattr(entry, f"{code}_remark") or ""
            has_mod = bool(getattr(entry, f"has_{code}"))
            if not has_mod and not status and not (remark or "").strip():
                continue
            StructureEntryServiceState.objects.update_or_create(
                structure_entry=entry,
                service_type=stype,
                defaults={
                    "inspection_status": status or "",
                    "remark": remark or "",
                },
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("infra_forms", "0012_copy_legacy_to_structureentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfraServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=160)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Infrastructure service type",
                "verbose_name_plural": "Infrastructure service types",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="StructureEntryServiceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not set"),
                            ("Completed", "Completed"),
                            ("Missing", "Missing"),
                            ("In progress", "In progress"),
                            ("Issue-attention", "Issue-attention"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("remark", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure_entry_states",
                        to="infra_forms.infraservicetype",
                    ),
                ),
                (
                    "structure_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_states",
                        to="infra_forms.structureentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Structure entry service state",
                "verbose_name_plural": "Structure entry service states",
                "ordering": ["structure_entry_id", "service_type__sort_order", "service_type_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="structureentryservicestate",
            constraint=models.UniqueConstraint(
                fields=("structure_entry", "service_type"),
                name="infra_entry_service_unique",
            ),
        ),
        migrations.RunPython(seed_service_types_and_backfill, noop_reverse),
    ]
