# Generated by Django 4.2 on 2026-03-11 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_add_product_model'),
        ('task_management', '0024_alter_task_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Alert type',
                'verbose_name_plural': 'Alert types',
                'db_table': 'alerts"."alert_types',
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Announcement type',
                'verbose_name_plural': 'Announcement types',
                'db_table': 'project"."announcement_types',
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField()),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='project.product')),
                ('type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='Alerts_Announcements.announcementtype')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'project"."Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_title', models.TextField()),
                ('alert_severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.DateTimeField()),
                ('alert_creator', models.ForeignKey(db_column='alert_creator_id', on_delete=django.db.models.deletion.CASCADE, related_name='created_alerts', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('alert_type', models.ForeignKey(db_column='alert_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='Alerts_Announcements.alerttype')),
                ('resolved_by', models.ForeignKey(blank=True, db_column='closed_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='closed_alerts', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('status', models.ForeignKey(db_column='status_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='task_management.taskstatus')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts"."Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
