# Generated by ChatGPT for implementing Attention model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Alerts_Announcements", "0002_alter_alert_resolved_by_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attention_title", models.TextField()),
                ("description", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "attention_creator",
                    models.ForeignKey(
                        db_column="attention_creator_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_attentions",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "db_table": 'alerts"."Attention',
                "ordering": ["-created_at"],
            },
        ),
    ]

