# Generated by ChatGPT for implementing target_employee on Attention
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Alerts_Announcements", "0003_attention"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attention",
            name="target_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                db_column="target_employee_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targeted_attentions",
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]

