# Generated by Django 4.2 on 2026-04-22 09:17

import adminpanel.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional document (e.g. PDF, image, Office). Max size enforced in API.', max_length=255, null=True, upload_to=adminpanel.models.vendor_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'doc', 'docx', 'xls', 'xlsx', 'txt'))]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='service',
            field=models.TextField(blank=True, default='', help_text='Optional description of services offered.'),
        ),
    ]
