# Generated by Django 4.2 on 2026-04-22 09:30

import adminpanel.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_vendor_service_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional scan or invoice (PDF, image, Office). Max size enforced in API.', max_length=255, null=True, upload_to=adminpanel.models.bill_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'doc', 'docx', 'xls', 'xlsx', 'txt'))]),
        ),
        migrations.AddField(
            model_name='bill',
            name='floor',
            field=models.CharField(blank=True, choices=[('3rd', '3rd floor'), ('4th', '4th floor'), ('both', 'Both floors')], help_text='3rd floor, 4th floor, or both (optional for legacy rows).', max_length=10, null=True),
        ),
    ]
