# Generated by Django 4.2 on 2026-04-22 11:40

import adminpanel.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def seed_default_expense_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model("adminpanel", "ExpenseCategory")
    for name in ("Grocery", "Stationary", "Document / Xerox"):
        ExpenseCategory.objects.get_or_create(name=name)


def seed_default_expense_categories_reverse(apps, schema_editor):
    # Intentionally no-op: do not delete category rows on migration reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_bill_floor_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Expense categories',
                'db_table': 'adminpanel"."Expensecategory',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_default_expense_categories, seed_default_expense_categories_reverse),
        migrations.CreateModel(
            name='ExpenseMonthlyAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Expense monthly advances',
                'db_table': 'adminpanel"."ExpenseMonthlyAdvance',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AddField(
            model_name='expensetracker',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional receipt or document (same types as bills/vendors). Max size enforced in API.', max_length=255, null=True, upload_to=adminpanel.models.expense_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'doc', 'docx', 'xls', 'xlsx', 'txt'))]),
        ),
        migrations.AddConstraint(
            model_name='expensemonthlyadvance',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='uniq_expense_advance_year_month'),
        ),
        migrations.AddField(
            model_name='expensetracker',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='adminpanel.expensecategory'),
        ),
    ]
