# Generated by Django 6.0.4 on 2026-06-05 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_expensecategory_expensemonthlyadvance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetracker',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='adminpanel.vendor'),
        ),
    ]
