# Generated by Django 4.2 on 2026-03-09 09:31

import Clients.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='status',
            field=models.ForeignKey(blank=True, default=Clients.models._get_leads_stage_id, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_profiles', to='Clients.currentclientstage'),
        ),
    ]
