# Generated by Django 4.2 on 2026-03-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_clientinteractionchannels_and_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='product_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional numeric value associated with the product (e.g. quote or amount).', max_digits=14, null=True),
        ),
    ]
