# Generated by Django 6.0.4 on 2026-06-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0007_clientprofile_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, help_text='When the creator last acknowledged a follow-up reminder for this lead.', null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='motive',
            field=models.TextField(blank=True),
        ),
    ]
