# Generated by Django 4.2 on 2026-05-21 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS certificates;",
            migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='EmployeeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', help_text='Short description of the certificate.', max_length=500)),
                ('s3_key', models.CharField(max_length=512)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(blank=True, default='', max_length=128)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False = soft-deactivated; row and S3 object are retained.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Certificate owner (creator).', on_delete=django.db.models.deletion.PROTECT, related_name='employee_certificates', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee certificate',
                'verbose_name_plural': 'Employee certificates',
                'db_table': 'certificates"."EmployeeCertificate',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='employeecertificate',
            index=models.Index(fields=['employee', 'is_active'], name='EmployeeCer_employe_36bd32_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecertificate',
            index=models.Index(fields=['-created_at'], name='EmployeeCer_created_897ea8_idx'),
        ),
    ]
