# Generated by Django 4.2 on 2026-02-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday_counter',
            field=models.SmallIntegerField(default=0),
        ),
    ]
