# Generated by Django 4.2 on 2026-02-25 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_profile_functions_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefunction',
            name='profile',
            field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile_functions', to='accounts.profile'),
        ),
    ]
