# Generated by Django 4.2 on 2026-03-04 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0039_alter_photo_upload_to_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSummary',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leave_summary', serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('total_leaves', models.PositiveIntegerField(default=0)),
                ('used_leaves', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'leave summary',
                'verbose_name_plural': 'leave summaries',
                'db_table': 'team_management"."leave_summary',
            },
        ),
        migrations.CreateModel(
            name='LeaveTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'leave type',
                'verbose_name_plural': 'leave types',
                'db_table': 'team_management"."leave_types',
            },
        ),
    ]
