# Generated by Django 4.2 on 2026-03-04 12:00

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_leaveapplicationdata_team_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplicationdata',
            name='MD_approval',
            field=models.ForeignKey(db_column='md_approval_id', default=accounts.models._get_pending_leave_status_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.leavestatus'),
        ),
        migrations.AlterField(
            model_name='leaveapplicationdata',
            name='half_day_slots',
            field=models.CharField(blank=True, choices=[('First_Half', 'First_Half'), ('Second_Half', 'Second_Half')], max_length=20, null=True),
        ),
    ]
