# Generated by Django 4.2 on 2026-03-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_leaveapplicationdata_md_approval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplicationdata',
            old_name='live_subject',
            new_name='leave_subject',
        ),
        migrations.AddField(
            model_name='leaveapplicationdata',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
