# Generated by Django 4.2 on 2026-03-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_rename_live_subject_leaveapplicationdata_leave_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesummary',
            name='emergency_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
