# Generated by Django 4.2 on 2026-03-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_leaveapplicationdata_alternative'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_logged_in',
            field=models.BooleanField(default=False, help_text='True when user is logged in, False when logged out.'),
        ),
    ]
