# Generated by Django 4.2 on 2026-04-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_profile_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], db_column='gender', max_length=20, null=True, verbose_name='gender'),
        ),
    ]
