# Generated by Django 4.2 on 2026-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesummary',
            name='casual_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavesummary',
            name='earn_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavesummary',
            name='menstrual_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
