# Generated by Django 4.2 on 2026-04-30 11:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_leavesummary_casual_leaves_leavesummary_earn_leaves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavesummary',
            name='casual_leaves',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='leavesummary',
            name='earn_leaves',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='leavesummary',
            name='menstrual_leaves',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5),
        ),
    ]
