# Generated by Django 6.0.4 on 2026-06-02 05:02

from datetime import datetime, time

from django.db import migrations, models
from django.utils import timezone


def backfill_applied_at(apps, schema_editor):
    LeaveApplicationData = apps.get_model("accounts", "LeaveApplicationData")
    ist = timezone.get_fixed_timezone(330)  # Asia/Kolkata (UTC+5:30)
    for row in LeaveApplicationData.objects.filter(applied_at__isnull=True).iterator():
        if not row.application_date:
            continue
        aware = timezone.make_aware(datetime.combine(row.application_date, time.min), ist)
        LeaveApplicationData.objects.filter(pk=row.pk).update(applied_at=aware)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0057_leavesummary_monthly_short_leave"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapplicationdata",
            name="applied_at",
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.RunPython(backfill_applied_at, migrations.RunPython.noop),
    ]
