# Generated by Django 6.0.4 on 2026-07-07 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_add_dm_function'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DmScoringTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('digital_media_target_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('digital_content_target_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='dm_scoring_targets', to='accounts.profile', to_field='Employee_id')),
                ('set_by', models.ForeignKey(blank=True, db_column='set_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_targets_set', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'DM scoring target',
                'verbose_name_plural': 'DM scoring targets',
                'db_table': 'login_details"."dm_scoring_targets',
            },
        ),
        migrations.CreateModel(
            name='DmWorkEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(choices=[('digital_media', 'Digital media'), ('digital_content', 'Digital content')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_work_entries_approved', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='dm_work_entries', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'DM work entry',
                'verbose_name_plural': 'DM work entries',
                'db_table': 'login_details"."dm_work_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dmscoringtarget',
            index=models.Index(fields=['profile', 'year', 'month'], name='dm_scoring__employe_792160_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dmscoringtarget',
            unique_together={('profile', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='dmworkentry',
            index=models.Index(fields=['created_by', '-created_at'], name='dm_work_ent_created_eba9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='dmworkentry',
            index=models.Index(fields=['status', '-created_at'], name='dm_work_ent_status_024225_idx'),
        ),
        migrations.AddIndex(
            model_name='dmworkentry',
            index=models.Index(fields=['content_type', '-created_at'], name='dm_work_ent_content_94d1de_idx'),
        ),
    ]
