"""
Django settings for ems project.

Generated by 'django-admin startproject' using Django 4.2.
For more information: https://docs.djangoproject.com/en/4.2/topics/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# =============================================================================
# Paths & Environment
# =============================================================================
BASE_DIR = Path(__file__).resolve().parent.parent
# load_dotenv(f"{BASE_DIR}/development.env")
load_dotenv(f"{BASE_DIR}/.env")

# =============================================================================
# Security
# =============================================================================
SECRET_KEY = os.getenv("SECRET_KEY")

# DEBUG is set conditionally below based on is_developement env var

ALLOWED_HOSTS = [
    "*",
    "employee-management-system-tmrl.onrender.com",
    "https://planeteye-employee-portal.onrender.com/",
    "https://planeteye-employee-portal.onrender.com",
    # "http://192.168.41.55:3000",
    # "http://192.168.41.55:3000/",
    "http://192.168.42.107:3000/",
    "http://192.168.42.107:3000",
]

# =============================================================================
# REST Framework
# =============================================================================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "ems.auth_utils.CsrfExemptSessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
    "EXCEPTION_HANDLER": "ems.utils.custom_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# =============================================================================
# Application Definition
# =============================================================================
INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "channels",
    "accounts",
    "task_management",
    "Messaging",
    "events",
    "project",
    "QuaterlyReports",
    "notifications",
    "adminpanel",
    "maintenance",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ems.urls"

# =============================================================================
# Templates
# =============================================================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# =============================================================================
# WSGI / ASGI
# =============================================================================
WSGI_APPLICATION = "ems.wsgi.application"
ASGI_APPLICATION = "ems.asgi.application"

# =============================================================================
# Channels (WebSockets, real-time)
# =============================================================================
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
        # Production: use Redis
        # "BACKEND": "channels_redis.core.RedisChannelLayer",
        # "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
    },
}
# =============================================================================
# Database – Connection pooling for AWS RDS (max 79 connections)
# =============================================================================
# Requires: pip install django-db-connection-pool[postgresql] (engine: dj_db_conn_pool)
# Formula: total_connections = GUNICORN_WORKERS × (POOL_SIZE + MAX_OVERFLOW).
# Keep total under ~65 so RDS (79) has headroom for admin/migrations.
# Effective max concurrent DB operations ≈ total_connections (limits peak users/requests).
DB_POOL_SIZE = int(os.getenv("DB_POOL_SIZE", "6"))
DB_MAX_OVERFLOW = int(os.getenv("DB_MAX_OVERFLOW", "8"))
DB_RECYCLE_SECONDS = int(os.getenv("DB_RECYCLE_SECONDS", "3600"))
# DB_POOL_TIMEOUT = int(os.getenv("DB_POOL_TIMEOUT", "45"))

DATABASES = {
    "default": {
        "ENGINE": "dj_db_conn_pool.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
        "OPTIONS": {
            "options": "-c search_path=events,task_management,notifications,project,quatery_reports,login_details,messaging,team_farm,team_infra,team_interns,team_management,public",
            "connect_timeout": 10,
        },
        "CONN_MAX_AGE": None,
        "DISABLE_SERVER_SIDE_CURSORS": True,
        "POOL_OPTIONS": {
            "POOL_SIZE": DB_POOL_SIZE,
            "MAX_OVERFLOW": DB_MAX_OVERFLOW,
            "RECYCLE": DB_RECYCLE_SECONDS,
            # "timeout": DB_POOL_TIMEOUT,
        },
    }
}

# =============================================================================
# Password Validation
# =============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =============================================================================
# Internationalization
# =============================================================================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

# =============================================================================
# Static & Media Files
# =============================================================================
STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# =============================================================================
# Misc
# =============================================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000
SESSION_SAVE_EVERY_REQUEST = True

# =============================================================================
# CORS
# =============================================================================
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://planeteye-employee-portal.onrender.com",
    "http://localhost:3000",
    "http://127.0.0.1:8000",
    # "http://192.168.41.55:3000",
    "http://192.168.42.107:3000",
]
CORS_ALLOW_METHODS = ["DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT"]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CSRF_TRUSTED_ORIGINS = [
    "https://employee-management-system-tmrl.onrender.com",
    "https://planeteye-employee-portal.onrender.com",
    # "http://192.168.41.55:3000",
    # "http://localhost:3000/",
    # "http://localhost:8000/",
    # "http://127.0.0.1:8000/",
    # "http://192.168.41.55:3000/",
    "http://192.168.41.120:3000/",
    "http://192.168.42.107:3000",
]

# =============================================================================
# WebSocket cross-origin (session-only auth)
# Cookies are sent automatically if: SameSite=None, Secure=True, CORS credentials.
# For cross-origin over HTTP in dev, use a same-origin proxy or local HTTPS.
# =============================================================================

# =============================================================================
# Environment-based Settings (Development vs Production)
# =============================================================================
if os.getenv("is_developement") == "True":
    DEBUG = True
    SESSION_COOKIE_SAMESITE = None
    CSRF_COOKIE_SAMESITE = None
    SESSION_COOKIE_HTTPONLY=False
    # For cross-origin WS in dev: use SESSION_COOKIE_SAMESITE = "None" and HTTPS.
else:
    DEBUG = False
    CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", False)
    SESSION_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", False)
    SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "None")
    CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "None")
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_HTTPONLY=False

# =============================================================================
# Logging (request logging for debugging)
# =============================================================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"simple": {"format": "%(asctime)s %(levelname)s %(message)s"}},
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "simple"}},
    "loggers": {
        "django.request": {"handlers": ["console"], "level": "INFO"},
        "django.server": {"handlers": ["console"], "level": "INFO"},
    },
}
