"""
Django settings for ems project.

Generated by 'django-admin startproject' using Django 4.2.
For more information: https://docs.djangoproject.com/en/4.2/topics/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# =============================================================================
# Paths & Environment
# =============================================================================
BASE_DIR = Path(__file__).resolve().parent.parent
# load_dotenv(f"{BASE_DIR}/development.env")
load_dotenv(f"{BASE_DIR}/.env")

# =============================================================================
# Security
# =============================================================================
SECRET_KEY = os.getenv("SECRET_KEY")

# DEBUG is set conditionally below based on is_developement env var

ALLOWED_HOSTS = [
    "*",
    "employee-management-system-tmrl.onrender.com",
    "https://employee-management-system-1-jwyn.onrender.com",
    "http://192.168.41.76:3000",
    "http://192.168.41.76:3000/",
    "http://192.168.42.107:3000/",
    "http://192.168.42.107:3000",
]

# =============================================================================
# REST Framework
# =============================================================================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "ems.auth_utils.CsrfExemptSessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
    "EXCEPTION_HANDLER": "ems.utils.custom_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# =============================================================================
# Application Definition
# =============================================================================
INSTALLED_APPS = [
    "daphne",
    "django_extensions",
    "storages",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "channels",
    "accounts",
    "task_management",
    "Messaging",
    "Calling",
    "events",
    "project",
    "Clients",
    "QuaterlyReports",
    "notifications",
    "adminpanel",
    "maintenance",
    "Alerts_Announcements",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "ems.middleware.CacheGetMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ems.urls"

# =============================================================================
# Templates
# =============================================================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# =============================================================================
# WSGI / ASGI
# =============================================================================
WSGI_APPLICATION = "ems.wsgi.application"
ASGI_APPLICATION = "ems.asgi.application"

# =============================================================================
# Render / 512MB memory limit
# Set env WEB_CONCURRENCY=1 (or 2) in Render dashboard to reduce Gunicorn/Uvicorn
# workers. Each worker loads full Django + Channels; 3–4 workers can exceed 512MB.
# Start command example: gunicorn ems.asgi:application -k uvicorn.workers.UvicornWorker
#   --workers ${WEB_CONCURRENCY:-1} --bind 0.0.0.0:$PORT
# =============================================================================

# =============================================================================
# Channels (WebSockets, real-time)
# InMemoryChannelLayer is process-local: with multiple workers/instances (e.g. on
# Render), each process has its own layer, so group_send from one process only
# reaches WebSockets in that process → some clients get notifications, others don't.
# Use Redis so all processes share one layer and every client gets notifications.
# On Render: add the "Redis" add-on and set REDIS_URL in the environment.
# =============================================================================
REDIS_URL = os.getenv("REDIS_URL")
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        },
    }
# else:
#     CHANNEL_LAYERS = {
#         "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
#     }

# =============================================================================
# Cache – Redis (same instance as Channels). GET API responses cached; invalidated on create/update.
# When REDIS_URL is missing, use DummyCache to avoid in-process memory growth (e.g. on 512MB Render).
# =============================================================================
CACHE_GET_TIMEOUT = int(os.getenv("CACHE_GET_TIMEOUT", "300"))  # 5 min default
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "KEY_PREFIX": "ems",
                "IGNORE_EXCEPTIONS": True,
            },
        }
    }

# =============================================================================
# Database – Connection pooling for AWS RDS (max 79 connections)
# =============================================================================
# Requires: pip install django-db-connection-pool[postgresql] (engine: dj_db_conn_pool)
# Total connections = GUNICORN_WORKERS × (POOL_SIZE + MAX_OVERFLOW). Keep under 65 for RDS 79.
# CONN_MAX_AGE=0 is required: returns connection to pool after each request so pool is not exhausted.
# DB_POOL_SIZE = int(os.getenv("DB_POOL_SIZE", "15"))
# DB_MAX_OVERFLOW = int(os.getenv("DB_MAX_OVERFLOW", "5"))
# DB_RECYCLE_SECONDS = int(os.getenv("DB_RECYCLE_SECONDS", "3600"))
# DB_POOL_TIMEOUT = int(os.getenv("DB_POOL_TIMEOUT", "60"))

# Schema-based apps: set on every cursor via ems.backends.postgresql (pool-safe).
# List the schema that contains auth_user (and django_session) first, then other app schemas. No public.
DB_SEARCH_PATH = os.getenv(
    "DB_SEARCH_PATH",
    "login_details,alerts,clients,events,task_management,notifications,project,quatery_reports,messaging,team_farm,team_infra,team_interns,team_management",
)

DATABASES = {
    "default": {
        "ENGINE": "ems.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
        # search_path is set on every cursor by ems.backends.postgresql (Neon pooler compatible).
        "OPTIONS": {
            "connect_timeout": 10,
            "sslmode": "require",
            "channel_binding": "require",
        },
        # "CONN_MAX_AGE": 0,
        # "DISABLE_SERVER_SIDE_CURSORS": True,
        # "POOL_OPTIONS": {
        #     "POOL_SIZE": DB_POOL_SIZE,
        #     "MAX_OVERFLOW": DB_MAX_OVERFLOW,
        #     "RECYCLE": DB_RECYCLE_SECONDS,
        #     "timeout": DB_POOL_TIMEOUT,
        # },
    }
}

# =============================================================================
# Password Validation
# =============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =============================================================================
# Internationalization
# =============================================================================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

# =============================================================================
# Static & Media Files
# =============================================================================
STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# =============================================================================
# AWS S3 storage
# =============================================================================
# Employee_Photo/ = profile photos (accounts). files/ = all other uploads (messaging, etc.).
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "ap-south-1")
AWS_S3_EMPLOYEE_PHOTO_PREFIX = os.getenv("AWS_S3_EMPLOYEE_PHOTO_PREFIX", "Employee_Photo/")
AWS_S3_FILES_PREFIX = os.getenv("AWS_S3_FILES_PREFIX", "files/")
AWS_S3_PRESIGNED_EXPIRY = int(os.getenv("AWS_S3_PRESIGNED_EXPIRY", "3600"))

# Default file storage: S3. Profile Photo_link uses upload_to="Employee_Photo/" so no extra AWS_LOCATION.
if AWS_STORAGE_BUCKET_NAME and AWS_ACCESS_KEY_ID:
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
    AWS_DEFAULT_ACL = None
    AWS_LOCATION = ""  # Path comes from model upload_to (Employee_Photo/)
else:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# S3 bucket CORS: use this when configuring the bucket (AWS Console or boto3 put_bucket_cors).
# ExposeHeaders allow the client to read Content-Disposition for download filenames.
AWS_S3_CORS_RULES = [
    {
        "AllowedHeaders": ["*"],
        "AllowedMethods": ["GET"],
        "AllowedOrigins": [
            os.getenv("AWS_S3_CORS_ORIGIN", "https://planeteye-employee-portal.onrender.com"),
        ],
        "ExposeHeaders": ["Content-Disposition", "Content-Type"],
    }
]

# =============================================================================
# Cron (X-CRON-KEY header for cron endpoints)
# =============================================================================
X_CRON_KEY = os.getenv("X_CRON_KEY","").strip()

# =============================================================================
# Misc
# =============================================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000

# Session: 12 hours global expiry; do not refresh on every request (fixed 12h from login).
SESSION_COOKIE_AGE = 12 * 60 * 60  # 12 hours in seconds
SESSION_SAVE_EVERY_REQUEST = False  # Session expires 12h after login, not extended per request
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Use SESSION_COOKIE_AGE

# =============================================================================
# CORS
# =============================================================================
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://planeteye-employee-portal.onrender.com",
    "https://employee-management-system-1-jwyn.onrender.com",
    "http://localhost:3000",
    "http://127.0.0.1:8000",
    "http://192.168.41.76:3000",
    # "http://192.168.41.55:3000",
    "http://192.168.42.107:3000",
]
CORS_ALLOW_METHODS = ["DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT"]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CSRF_TRUSTED_ORIGINS = [
    "https://employee-management-system-1-jwyn.onrender.com",
    "https://planeteye-employee-portal.onrender.com",
    # "http://192.168.41.55:3000",
    "http://192.168.41.76:3000",
    # "http://localhost:3000/",
    # "http://localhost:8000/",
    # "http://127.0.0.1:8000/",
    # "http://192.168.41.55:3000/",
    "http://192.168.41.120:3000/",
    "http://192.168.42.107:3000",
    "http://localhost:3001",
]

# =============================================================================
# WebSocket cross-origin (session-only auth)
# Cookies are sent automatically if: SameSite=None, Secure=True, CORS credentials.
# For cross-origin over HTTP in dev, use a same-origin proxy or local HTTPS.
# =============================================================================

# =============================================================================
# Environment-based Settings (Development vs Production)
# =============================================================================
if os.getenv("is_developement") == "True":
    DEBUG = True
    SESSION_COOKIE_SAMESITE = None
    CSRF_COOKIE_SAMESITE = None
    SESSION_COOKIE_HTTPONLY=False
    # SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE = True
    # For cross-origin WS in dev: use SESSION_COOKIE_SAMESITE = "None" and HTTPS.
else:
    DEBUG = True
    CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", False)
    SESSION_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", False)
    SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "None")
    CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "None")
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_HTTPONLY=False
    
# Add Cloudflare Tunnel HTTPS URL when using cloudflared (set in .env: CLOUDFLARE_TUNNEL_ORIGIN=https://xxx.trycloudflare.com)
_cloudflare_origin = os.getenv("CLOUDFLARE_TUNNEL_ORIGIN", "").strip().rstrip("/")
if _cloudflare_origin:
    CSRF_TRUSTED_ORIGINS.append(_cloudflare_origin)

# =============================================================================
# Logging (request logging for debugging)
# =============================================================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"simple": {"format": "%(asctime)s %(levelname)s %(message)s"}},
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "simple"}},
    "loggers": {
        "django.request": {"handlers": ["console"], "level": "INFO"},
        "django.server": {"handlers": ["console"], "level": "INFO"},
    },
}

# Optional: also set search_path on new connections (redundant with ems.backends.postgresql which sets it on every cursor).
import ems.db  # noqa: E402
