# Generated by Django 6.0.5 on 2026-05-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
