# Generated by Django 6.0.5 on 2026-05-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_asset_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
