# Generated by Django 4.2 on 2026-04-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0047_profile_is_logged_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(choices=[("Hardware", "Hardware"), ("Software", "Software")], max_length=20)),
                ("asset_type", models.CharField(max_length=100)),
                ("provider", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                ("admin_approval", models.CharField(choices=[("Pending", "Pending"), ("Approved", "Approved"), ("Rejected", "Rejected")], default="Pending", max_length=10)),
                ("md_approval", models.CharField(choices=[("Pending", "Pending"), ("Approved", "Approved"), ("Rejected", "Rejected")], default="Pending", max_length=10)),
                ("status", models.CharField(choices=[("Active", "Active"), ("Inactive", "Inactive"), ("Expired", "Expired"), ("Available", "Available")], default="Available", max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="asset_requests_assigned", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="asset_requests_created", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "department",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="asset_requests", to="accounts.departments"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]

