# Generated by Django 4.2 on 2026-03-16 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR_Assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(db_column='answer_id', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_responses', to='HR_Assessment.answer')),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='hr_assessment_responses', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_responses', to='HR_Assessment.question')),
            ],
            options={
                'verbose_name': 'candidate response',
                'verbose_name_plural': 'candidate responses',
                'db_table': 'emp_assessment"."hr_assessment_candidate_responses',
                'ordering': ['-date', '-time', 'candidate_id'],
            },
        ),
    ]
