# Generated by Django 4.2 on 2026-05-20 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS tour_advance;",
            migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='TourAdvanceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_advance_member_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour advance member',
                'db_table': 'tour_advance"."TourAdvanceMember',
            },
        ),
        migrations.CreateModel(
            name='TourAdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(blank=True, default='', max_length=100)),
                ('project', models.CharField(blank=True, default='', max_length=255)),
                ('division', models.CharField(blank=True, default='', max_length=255)),
                ('from_location', models.CharField(blank=True, default='', max_length=255)),
                ('from_location_pincode', models.CharField(blank=True, default='', max_length=20)),
                ('to_location', models.CharField(blank=True, default='', max_length=255)),
                ('to_location_pincode', models.CharField(blank=True, default='', max_length=20)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('purpose_of_visit', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('no_of_days', models.PositiveIntegerField(default=0)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_advance_created', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='tour_advance_memberships', through='tour_advance.TourAdvanceMember', to=settings.AUTH_USER_MODEL)),
                ('primary_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_advance_primary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour advance request',
                'db_table': 'tour_advance"."TourAdvanceRequest',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='touradvancemember',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='tour_advance.touradvancerequest'),
        ),
        migrations.CreateModel(
            name='TourAdvanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=512)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(blank=True, default='', max_length=128)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tour_advance.touradvancerequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_advance_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour advance attachment',
                'db_table': 'tour_advance"."TourAdvanceAttachment',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='touradvancemember',
            unique_together={('request', 'member')},
        ),
    ]
