# Generated by Django 4.2 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour_advance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="touradvanceattachment",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
