# Generated by Django 4.2 on 2026-03-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0018_missedcallcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissedCallCount',
        ),
    ]
