# Generated by Django 4.2 on 2026-04-28 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('intern', 'intern'), ('employee', 'employee'), ('teamlead', 'teamlead'), ('md', 'md')], db_index=True, max_length=20)),
                ('metrics', models.JSONField(default=dict)),
                ('markdown', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Nullable for org-wide summaries (type=md).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aisummary',
            index=models.Index(fields=['type', '-created_at'], name='ai_summary__type_519cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='aisummary',
            index=models.Index(fields=['user', 'type', '-created_at'], name='ai_summary__user_id_cc8432_idx'),
        ),
    ]
