# Generated by Django 4.2 on 2026-03-12 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Calling', '0002_call_groupcall_missed_status_and_screen_shared'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedCallCount',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='messaging_missed_call_count', serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('missed_call_count', models.IntegerField(db_column='missed_call_count', default=0)),
            ],
            options={
                'verbose_name': 'Missed call count',
                'verbose_name_plural': 'Missed call counts',
                'db_table': 'messaging"."MissedCallCount',
            },
        ),
    ]
