# Generated by Django 4.2 on 2026-02-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuaterlyReports', '0006_functionsentries_co_author_share_with_approved_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_department_head_and_subhead',
            name='quater',
        ),
        migrations.AlterField(
            model_name='monthly_department_head_and_subhead',
            name='meeting_sub_head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
