# Generated by Django 4.2 on 2026-02-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuaterlyReports', '0007_remove_monthly_department_head_and_subhead_quater_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_department_head_and_subhead',
            name='Meeting_head',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='monthly_department_head_and_subhead',
            name='Sub_Head_D1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_department_head_and_subhead',
            name='Sub_Head_D2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_department_head_and_subhead',
            name='Sub_Head_D3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monthly_department_head_and_subhead',
            name='meeting_sub_head',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
