# Generated by Django 4.2 on 2026-02-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0024_alter_task_options'),
        ('QuaterlyReports', '0009_rename_functionsentries_status_to_final_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionsentries',
            name='final_Status',
            field=models.ForeignKey(blank=True, db_column='status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions_entries_final', to='task_management.taskstatus'),
        ),
        migrations.AlterField(
            model_name='functionsentries',
            name='shared_Status',
            field=models.ForeignKey(blank=True, db_column='final_status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions_entries_shared', to='task_management.taskstatus'),
        ),
    ]
