# Generated by Django 4.2 on 2026-03-09 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_add_product_model'),
        ('task_management', '0024_alter_task_options'),
        ('QuaterlyReports', '0013_functionsentries_co_author_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedactions',
            options={'ordering': ['grp', '-deadline']},
        ),
        migrations.AddField(
            model_name='functionsentries',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functions_entries', to='project.product'),
        ),
        migrations.AddField(
            model_name='plannedactions',
            name='action',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedactions',
            name='assigned_to',
            field=models.ForeignKey(db_column='assigned_to', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='assigned_help_to'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedactions',
            name='deadline',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedactions',
            name='grp',
            field=models.ForeignKey(db_column='grp', default=None, on_delete=django.db.models.deletion.CASCADE, to='QuaterlyReports.grps', verbose_name='grp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plannedactions',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_actions', to='project.product'),
        ),
        migrations.AddField(
            model_name='plannedactions',
            name='status',
            field=models.ForeignKey(db_column='status', default=None, on_delete=django.db.models.deletion.CASCADE, to='task_management.taskstatus', verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesstatistics',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_statistics', to='project.product'),
        ),
        migrations.AlterModelTable(
            name='plannedactions',
            table='PlannedActions',
        ),
    ]
