# Generated by Django 4.2 on 2026-03-16 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QuaterlyReports', '0015_usersentries_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesstatistics',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='salesstatistics',
            name='grp',
        ),
        migrations.AddField(
            model_name='salesstatistics',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
