# Generated by ChatGPT on 2026-03-24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerPanelEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("business_name", models.CharField(db_index=True, max_length=255)),
                ("office_address", models.TextField(blank=True, null=True)),
                ("representative_name", models.CharField(blank=True, max_length=255, null=True)),
                ("representative_contact_number", models.CharField(blank=True, max_length=100, null=True)),
                ("serial_no", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("product", models.CharField(blank=True, max_length=255, null=True)),
                ("service", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("value", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("tax_percent", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("total", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=models.deletion.CASCADE,
                        related_name="customer_panel_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "customer panel entry",
                "verbose_name_plural": "customer panel entries",
                "db_table": 'customer_panel"."entry',
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="cust_panel_created_idx"),
                    models.Index(fields=["business_name"], name="cust_panel_business_idx"),
                    models.Index(fields=["serial_no"], name="cust_panel_serial_idx"),
                ],
            },
        ),
    ]

