# Generated by ChatGPT on 2026-03-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CustomerPanel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerPanelAmountLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry",
                    models.ForeignKey(
                        db_column="entry_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amount_logs",
                        to="CustomerPanel.customerpanelentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer panel amount log",
                "verbose_name_plural": "customer panel amount logs",
                "db_table": 'customer_panel"."amount_log',
                "ordering": ["-date", "-created_at"],
                "indexes": [models.Index(fields=["entry_id", "-date"], name="cust_panel_log_entry_date_idx")],
            },
        ),
    ]

