# Generated by Django 4.2 on 2026-02-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_receipient_created_at_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='Notificatio_receipi_391d76_idx',
            old_name='notif_rec_created_idx',
        ),
    ]
